import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(process.cwd())

function read(path: string): string {
    return readFileSync(resolve(ROOT, path), 'utf-8')
}

describe('operation intelligence frontend structure', () => {
    it('registers an authenticated route and sidebar item', () => {
        const moduleSource = read('src/app/modules/operation-intelligence/module.ts')

        expect(moduleSource).toContain("id: 'operation-intelligence'")
        expect(moduleSource).toContain("path: '/operation-intelligence'")
        expect(moduleSource).toContain("path: '/operation-intelligence/knowledge-graph'")
        expect(moduleSource).toContain("titleKey: 'sidebar.operationIntelligence'")
        expect(moduleSource).toContain("icon: 'businessIntelligence'")
        expect(moduleSource).not.toContain("titleKey: 'sidebar.operationKnowledgeGraph'")
        expect(moduleSource).toContain('end: true')
        expect(moduleSource).toContain("access: 'authenticated'")
    })

    it('declares runtime URL and secret configuration in code and examples', () => {
        const runtimeSource = read('src/config/runtime.ts')
        const standalone = JSON.parse(read('../web-app/config.standalone.json.example')) as Record<string, unknown>
        const embed = JSON.parse(read('../web-app/config.embed.json.example')) as Record<string, unknown>

        expect(runtimeSource).toContain('operationIntelligenceServiceUrl')
        expect(runtimeSource).toContain('operationIntelligenceSecretKey')
        expect(runtimeSource).toContain('operationIntelligenceKnowledgeGraph')
        expect(runtimeSource).toContain('DEFAULT_KNOWLEDGE_GRAPH_COLLAPSED_RELATION_RULES')
        expect(runtimeSource).toContain('DEFAULT_KNOWLEDGE_GRAPH_RESOURCE_TREE_HIERARCHY_RULES')
        expect(runtimeSource).toContain('resourceTreeHierarchyRules')
        expect(runtimeSource).toContain('OPERATION_INTELLIGENCE_SERVICE_URL')
        expect(runtimeSource).toContain('OPERATION_INTELLIGENCE_SECRET_KEY')
        expect(runtimeSource).toContain("pathPrefix: '/operation-intelligence'")
        expect(standalone.operationIntelligenceServiceUrl).toBe('http://127.0.0.1:8096')
        expect(standalone.operationIntelligenceSecretKey).toBeTruthy()
        expect(standalone.operationIntelligenceKnowledgeGraph).toBeTruthy()
        expect(embed.operationIntelligenceServiceUrl).toBe('')
        expect(embed.operationIntelligenceSecretKey).toBeTruthy()
        expect(embed.operationIntelligenceKnowledgeGraph).toBeTruthy()
    })

    it('routes all API calls to operation-intelligence with secret headers', () => {
        const apiSource = read('src/services/operationIntelligenceAPI.ts')

        expect(apiSource).toContain('OPERATION_INTELLIGENCE_SERVICE_URL')
        expect(apiSource).toContain('gatewayHeaders')
        expect(apiSource).toContain('/qos/getHealthIndicator')
        expect(apiSource).toContain('/qos/getResourceIndicatorDetail')
        expect(apiSource).toContain('/qos/getContributionData')
        expect(apiSource).toContain('/qos/getProductConfigRule')
        expect(apiSource).toContain('/qos/getEnvironments')
        expect(apiSource).toContain('/graph/resources/tree')
        expect(apiSource).toContain('/graph/diagnosis/context')
    })

    it('keeps operation-intelligence user-facing copy aligned in both locales', () => {
        const en = JSON.parse(read('src/i18n/en.json'))
        const zh = JSON.parse(read('src/i18n/zh.json'))

        expect(en.sidebar.operationIntelligence).toBe('Operation Intelligence')
        expect(zh.sidebar.operationIntelligence).toBe('智能运维')
        expect(Object.keys(en.operationIntelligence).sort()).toEqual(Object.keys(zh.operationIntelligence).sort())
        expect(Object.keys(en.operationIntelligence.knowledgeGraph).sort())
            .toEqual(Object.keys(zh.operationIntelligence.knowledgeGraph).sort())
        expect(Object.keys(en.operationIntelligence.workspaceTabs).sort())
            .toEqual(Object.keys(zh.operationIntelligence.workspaceTabs).sort())
        expect(en.operationIntelligence.title).toBeTruthy()
        expect(zh.operationIntelligence.title).toBeTruthy()
    })

    it('uses module-local files without depending on the removed health-curve module', () => {
        const pageSource = read('src/app/modules/operation-intelligence/pages/OperationIntelligencePage.tsx')
        const chartSource = read('src/app/modules/operation-intelligence/components/OperationIntelligenceChart.tsx')
        const filtersSource = read('src/app/modules/operation-intelligence/components/OperationIntelligenceFilters.tsx')

        expect(pageSource).toContain('operationIntelligenceAPI')
        expect(pageSource).toContain('OperationIntelligenceChart')
        expect(pageSource).toContain('OperationIntelligenceFilters')
        expect(pageSource).not.toContain('healthCurve')
        expect(chartSource).not.toContain('HealthCurve')
        expect(filtersSource).not.toContain('HealthCurve')
    })

    it('uses shared UI primitives instead of feature-local chrome', () => {
        const pageSource = read('src/app/modules/operation-intelligence/pages/OperationIntelligencePage.tsx')
        const filtersSource = read('src/app/modules/operation-intelligence/components/OperationIntelligenceFilters.tsx')
        const scoreCardsSource = read('src/app/modules/operation-intelligence/components/DimensionScoreCards.tsx')
        const contributionSource = read('src/app/modules/operation-intelligence/components/ContributionAnalysis.tsx')
        const styles = read('src/app/modules/operation-intelligence/styles/operation-intelligence.css')

        expect(pageSource).toContain("../../../platform/ui/primitives/PageHeader")
        expect(pageSource).toContain("../../../platform/ui/primitives/SectionCard")
        expect(pageSource).toContain("../../../platform/ui/primitives/AnalyticsTableCard")
        expect(pageSource).toContain("../../../platform/ui/primitives/ChartHeaderLegend")
        expect(filtersSource).toContain("../../../platform/ui/filters/FilterSelect")
        expect(filtersSource).toContain("../../../platform/ui/primitives/Button")
        expect(filtersSource).toContain('operation-intelligence-control-panel')
        expect(filtersSource).toContain('operation-intelligence-score-chip')
        expect(scoreCardsSource).toContain("../../../platform/ui/primitives/StatCard")
        expect(contributionSource).toContain("../../../platform/ui/primitives/PieDistributionCard")
        expect(styles).not.toContain('!important')
        expect(styles).not.toContain('.score-card')
        expect(styles).not.toContain('.operation-intelligence-filters button')
    })

    it('adds a knowledge graph workbench under operation-intelligence', () => {
        const pageSource = read('src/app/modules/operation-intelligence/pages/KnowledgeGraphPage.tsx')
        const workspaceSource = read('src/app/modules/operation-intelligence/pages/OperationIntelligenceWorkspacePage.tsx')
        const apiSource = read('src/services/operationIntelligenceAPI.ts')
        const styles = read('src/app/modules/operation-intelligence/styles/operation-intelligence.css')

        expect(workspaceSource).toContain('OperationIntelligencePage')
        expect(workspaceSource).toContain('KnowledgeGraphPage')
        expect(workspaceSource).toContain('config-tabs')
        expect(pageSource).toContain('getResourceTree')
        expect(pageSource).toContain('querySubgraph')
        expect(pageSource).toContain('listGraphEnvironments')
        expect(pageSource).toContain('listOntologies')
        expect(pageSource).toContain('importGraph')
        expect(pageSource).toContain('importOntology')
        expect(pageSource).toContain('exportGraph')
        expect(pageSource).toContain('deleteOntology')
        expect(pageSource).toContain('deleteEntities')
        expect(pageSource).toContain('downloadJson')
        expect(pageSource).toContain('handleExportOntology')
        expect(pageSource).toContain('handleExportEntities')
        expect(pageSource).toContain('handleImportOntologyFile')
        expect(pageSource).toContain('handleImportEntitiesFile')
        expect(pageSource).toContain('parseOntology')
        expect(pageSource).toContain('buildOntologyGraph')
        expect(pageSource).toContain('buildEntityOverviewGraph')
        expect(pageSource).toContain('buildEntitySubgraph')
        expect(pageSource).toContain('buildCollapsedRelationIds')
        expect(pageSource).toContain('buildResourceTreeViewGroups')
        expect(pageSource).toContain('matchesHierarchyRule')
        expect(pageSource).toContain('collapsedChildrenCount')
        expect(pageSource).toContain('expandedEntityGraphNodeIds')
        expect(pageSource).toContain('expandedResourceEntityIds')
        expect(pageSource).toContain('GraphCanvas')
        expect(pageSource).toContain('activeGraphTab')
        expect(pageSource).toContain('subgraphUpstreamHops')
        expect(pageSource).toContain('subgraphDownstreamHops')
        expect(pageSource).toContain('buildDirectedLayers')
        expect(pageSource).toContain('getResourceCardFields')
        expect(pageSource).toContain('environmentOptions')
        expect(pageSource).toContain('ontologyOptions')
        expect(pageSource).toContain('expandedResourceGroupIds')
        expect(pageSource).toContain('selectedResourceEntity')
        expect(pageSource).toContain('ontologyId')
        expect(pageSource).toContain("value={envCode}")
        expect(pageSource).toContain("role=\"tablist\"")
        expect(pageSource).toContain("../../../platform/ui/primitives/PageHeader")
        expect(pageSource).toContain("../../../platform/ui/primitives/SectionCard")
        expect(apiSource).toContain('/graph/admin/import')
        expect(apiSource).toContain('/graph/admin/export')
        expect(apiSource).toContain('/graph/subgraph')
        expect(apiSource).toContain('/graph/admin/delete-entities')
        expect(apiSource).toContain('/graph/admin/delete-ontology')
        expect(apiSource).toContain('/graph/environments')
        expect(apiSource).toContain('/graph/ontologies')
        expect(apiSource).toContain('upstreamHops')
        expect(apiSource).toContain('downstreamHops')
        expect(apiSource).toContain('Math.max(upstreamHops, downstreamHops)')
        expect(styles).toContain('.kg-workbench')
        expect(styles).toContain('.kg-workspace')
        expect(styles).toContain('.kg-page-tabs')
        expect(styles).toContain('.kg-tree-node')
        expect(styles).toContain('.kg-tree-group-title')
        expect(styles).toContain('.kg-resource-layout')
        expect(styles).toContain('.kg-resource-card')
        expect(styles).toContain('.kg-resource-card-meta')
        expect(styles).toContain('.kg-resource-card-tag')
        expect(styles).toContain('.kg-graph-canvas')
        expect(styles).toContain('.kg-graph-node')
        expect(styles).toContain('.kg-graph-node-collapsed')
        expect(styles).toContain('.kg-node-popover')
    })
})
