server:
  port: 8095

spring:
  application:
    name: skill-market
  config:
    import: optional:file:./config.yaml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB


management:
  endpoints:
    web:
      exposure:
        include: health,info
