spring:
  application:
    name: finops
  config:
    import: "optional:file:${CONFIG_PATH:./config.yaml}"

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8097
